---
title: "untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}

library(tidyverse);
library(readr);


ICPMS_imported <- read.csv("~/Chem 313/soil_ICPMS_real/Soil_data/ICPMS_Data.csv", skip = 1, na="N/A")
sample_key <- read.csv("~/Chem 313/soil_ICPMS_real/Soil_data/Sample_Key.csv", skip=0)

view(ICPMS_imported)
view(sample_key)
```

```{r}
#tidying data
RSD_data <- ICPMS_imported %>%
select(Cr52 = CPS.RSD,
Cr53 = CPS.RSD.1,
As75 = CPS.RSD.2,
Cd111 = CPS.RSD.3,
Cd114 = CPS.RSD.4,
Pb208 = CPS.RSD.5,
Ge_RSD = CPS.RSD.7,
Sample.Key)%>%

pivot_longer(1:6,
names_to = "metal",
values_to = "RSD")
```

```{r}
ICPMS_tidy <- ICPMS_imported %>%
select(Cr52 = CPS,
Cr53 = CPS.1,
As75 = CPS.2,
Cd111 = CPS.3,
Cd114 = CPS.4,
Pb208 = CPS.5,
Ge72 = CPS.7,
Sample.Key)%>%

pivot_longer(1:6,
names_to = "metal",
values_to = "CPS")%>%
  
  mutate(RSD = RSD_data$RSD/RSD_data$Ge_RSD,
         CPS = CPS/Ge72)%>%
  select(-Ge72)

all(RSD_data$Sample.Key==ICPMS_tidy$Sample.Key, RSD_data$metal==ICPMS_tidy$metal)

ICPMS_tidy
```

```{r}
ICPMS_merged <- merge(ICPMS_tidy, sample_key)

ICPMS_merged
```

```{r, warning=FALSE}
rm(list=setdiff(ls(), "ICPMS_merged"))
```

```{r}
write.csv(ICPMS_merged, file = "~/Chem 313/soil_ICPMS_real/data/tidy_ICPMS.csv")
```
